# Generated by Django 5.1.6 on 2025-02-21 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'db_table': 'car',
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('context', models.TextField(blank=True)),
                ('horsepower', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='cars/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avtoapp.car')),
            ],
            options={
                'verbose_name': 'Mashina',
                'verbose_name_plural': 'Mashina_brendi',
                'db_table': 'mashinalar',
                'ordering': ['year'],
            },
        ),
    ]
