# Generated by Django 5.1.6 on 2025-02-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avtoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['brand'], 'verbose_name': 'Car_brand', 'verbose_name_plural': 'Car_brands'},
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['year'], 'verbose_name': 'cara', 'verbose_name_plural': 'cars'},
        ),
        migrations.AlterModelTable(
            name='cars',
            table='cars',
        ),
    ]
