# Generated by Django 5.1.6 on 2025-02-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avtoapp', '0002_alter_car_options_alter_cars_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car_s',
        ),
    ]
